# Generated by Django 3.0.3 on 2020-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pages',
        ),
        migrations.AddField(
            model_name='article',
            name='pageRecord',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='pageTotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
