# Generated by Django 3.0.3 on 2020-08-08 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200702_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='text',
            field=models.TextField(default='오늘 읽은 부분에 대한 감상을 입력하세요.'),
        ),
    ]
