# Generated by Django 3.0.3 on 2020-08-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200808_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='diary.Article'),
            preserve_default=False,
        ),
    ]
